version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: anoblet
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: workbox-window
    versions:
    - 6.0.2
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: workbox-build
    versions:
    - 6.0.2
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  registries:
  - git-github-com
